language: php

php:
  - 7.0
  - 7.1

services:
    - mysql

before_script:
  - cp .travis.env .env
  - mysql -e 'create database itmayziii;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan migrate:refresh --seed
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"

script: phpunit