version: '3'
services:
  web:
    container_name: fullheapdeveloper_web
    image: nginx:latest
    working_dir: /site
    ports:
    - 8080:80
    volumes:
    - ./:/site
    - ./docker-config/nginx/site.conf:/etc/nginx/conf.d/default.conf
    tty: true
    networks:
    - backend
    depends_on:
    - mysql
    - php

  php:
    container_name: fullheapdeveloper_php
    image: itmayziii/fullheapdeveloper-php:dev-1
    working_dir: /site
    ports:
    - 9000:9000
    volumes:
    - ./:/site
    networks:
    - backend

  mysql:
    container_name: fullheapdeveloper_mysql
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=C12H22o11
    - MYSQL_DATABASE=fullheapdeveloper
    - MYSQL_PASSWORD=Password1
    - MYSQL_USER=itmayziii
    ports:
    - 3306:3306
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
    - backend

  mongo:
    container_name: fullheapdeveloper_mongo
    image: mongo:4
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=Password1
    - MONGO_INITDB_DATABASE=fullheapdeveloper
    ports:
    - 27017:27017
    volumes:
    - ./data/mongo:/data/db
    networks:
    - backend

  redis:
    container_name: fullheapdeveloper_redis
    image: redis:4.0.8
    volumes:
    - ./docker-config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - 6379:6379
    command: redis-server --requirepass Password1
    networks:
    - backend

networks:
  backend:
