version: '3'
services:
  blog-api-web:
      container_name: blog-api-web
      image: itmayziii/nginx-php70:latest
      ports:
          - 8080:80
      links:
          - blog-api-db
      volumes:
          - ./:/home/forge/default
      tty: true
  blog-api-db:
      container_name: blog-api-db
      image: mysql:latest
      environment:
          - MYSQL_ROOT_PASSWORD=C12H22o11
          - MYSQL_DATABASE=itmayziii
          - MYSQL_PASSWORD=Password1
          - MYSQL_USER=forge
      ports:
          - 3306:3306