version: '3'
services:
  web:
      container_name: blog_api_web
      image: itmayziii/nginx-php70:latest
      ports:
          - 8080:80
      links:
          - mysql
      volumes:
          - ./:/home/forge/default
      tty: true
      networks:
        - backend

  mysql:
      container_name: blog_api_db
      image: mysql:latest
      environment:
          - MYSQL_ROOT_PASSWORD=C12H22o11
          - MYSQL_DATABASE=itmayziii
          - MYSQL_PASSWORD=Password1
          - MYSQL_USER=forge
      ports:
          - 3306:3306
      networks:
        - backend

networks:
  backend: